export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "../images/d1.jpg",
      price: "$60",
      brand: "Nike",
      rating: 4.5,
      numreviews: 40,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "../images/d1.jpg",
      price: "$50",
      brand: "Nike",
      rating: 4.3,
      numreviews: 12,
    },
    {
      _id: "3",
      name: "Pant",
      category: "Pants",
      image: "../images/d1.jpg",
      price: "$90",
      brand: "Nike",
      rating: 4.7,
      numreviews: 14,
    },
    {
      _id: "4",
      name: "Pant Showroom",
      category: "Pants",
      image: "../images/d1.jpg",
      price: "$45",
      brand: "Nike",
      rating: 3.9,
      numreviews: 1,
    },
  ],
};